### PR TITLE
Changed UI

### PR DESCRIPTION
**Pull request by binayshaw7777**

### CODE REVIEW

**Comment by Kajal13081** [comment]
Please do follow PR template from now onwards while raising PR. I will review the code soon.

**Comment by binayshaw7777** [comment]
Sure, I'll keep that in mind.

**Comment by Kajal13081** [comment]
One changes needed only then we are good to go.

**Comment by binayshaw7777** [comment]
What is the change?

**Comment by Kajal13081** [comment]
> What is the change?
values/themes.xml me do it dark action bar. 
we need to have action bar.

**Comment by binayshaw7777** [comment]
I was also thinking about doing other medium issues as well, shall I made the change along with that? or what shall I do?

**Comment by Kajal13081** [comment]
> Oh, I don't remember exactky. I aleady pushed. What shall I do now?

there will be edit option, edit and commit again.
image

**Comment by Kajal13081** [comment]
> I was also thinking about doing other medium issues as well, shall I made the change along with that? or what shall I do?
each issue will have different PRs. So if you want to solve any issue do it but update JWOC branch first. Then push the codes and raise PR here.

**Comment by binayshaw7777** [comment]
Please check. I made changes

**Review by Kajal13081 — APPROVED** [review]

**Comment by Kajal13081** [comment]
Merged successfully. 🎉

**Comment by binayshaw7777** [comment]
Thanks :D

**Pull request merged**
