### PR TITLE
Splash Screen Completed

### PR DESCRIPTION
**Pull request by aritra-tech**
I have sone the Splash Screen Activity.
Issue No 6

### CODE REVIEW

**Comment by Kajal13081** [comment]
share the screenshot of changes you did @aritra-tech

**Comment by aritra-tech** [comment]
SplashScreen(XML)
SplashScreen(Java)

You can see the icon when you will run your app.

**Comment by Kajal13081** [comment]
The app is running properly na?

**Comment by aritra-tech** [comment]
> The app is running properly na?

Yes @Kajal13081 
You, can check it if you want

**Review by Kajal13081 — APPROVED** [review]

**Pull request merged**
