### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by wasimreja**
## JWOC Project 📝

Thanks for your participation in this project for JWOC. 
The contribution will help you get a nice understanding of Android Development. 

Stay determined, stay motivated and Happy Contributing :)

All the best :)

<hr>

## Description 📜

Update README.md file.

Fixes # 63

<hr>

## Please make sure to follow these points ✅

- [x] I have performed a self-review of my own code or work.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] My Pull Request title is in format <code>< issue name ></code> eg <code>design app icon</code>
- [ ] I will upload screenshot/Gif of what I have contributed.
- [x] I'm JWOC'22 contributor
  
<hr>

## Screenshots / Gif 📸

<hr>

### Thank you!
Your part is over after your pull request is made. Your Pull Request will be merged soon if approved by maintainers. Happy contributing.

### CODE REVIEW

**Comment by Kajal13081** [comment]
Hey @wasimreja please raise the PR in JWOC branch not main branch.

**Comment by wasimreja** [comment]
Okay!

**Comment by wasimreja** [comment]
@Kajal13081 I'm creating a new PR as it's showing merge conflicts.

**Comment by Kajal13081** [comment]
> @Kajal13081 I'm creating a new PR as it's showing merge conflicts.

Update JWOC branch then raise the PR.

**Comment by wasimreja** [comment]
@Kajal13081 I have updated JWOC branch and raised a new PR.

**Pull request closed without merging**
